target 'TagQ' do
    pod 'AFNetworking'
    pod 'YYModel'
    pod 'SDWebImage','~> 3.7'
    pod 'StreamKit'
    pod 'Masonry'
    pod 'MBProgressHUD'#,'~> 0.9'
    pod 'AMap3DMap-NO-IDFA'
    pod 'AMapLocation-NO-IDFA'
    pod 'AMapSearch-NO-IDFA'
    pod 'SVProgressHUD'
    pod 'pop'
    pod 'YYText'
    pod 'ViewDeck'
    pod 'FHCategory'
    pod 'IQKeyboardManager'
    pod 'YYCategories'
    pod 'UICollectionViewLeftAlignedLayout'
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'TMarco'
    pod 'TCacheService'
    pod 'MGSwipeTableCell'
    pod 'JSBadgeView'
    pod 'MJRefresh'
    pod 'FMDB'
    pod 'GPUImage'
    pod 'QQHeader'
    pod 'BarrageRenderer'
    pod 'BCGenieEffect'
    pod 'FDFullscreenPopGesture'
#    pod 'DZNEmptyDataSet'
    ##友盟
    pod 'UMengUShare/UI'
    pod 'UMengUShare/Social/ReducedQQ'
    pod 'UMengUShare/Social/ReducedSina'
    
    ##环信
    pod 'HyphenateLite'
#    pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'

end
